artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  download_zip_file_dir: artifacts/data_ingestion/data.zip
  unzip_zipped_file_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_dir: artifacts/model
  train_data: artifacts/data_transformation/train.csv
  test_data: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data: artifacts/data_transformation/test.csv
  model_path: artifacts/model/model.joblib
  metric_file: artifacts/model_evaluation/metrics.json

dvc: 
  remote: ""