# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - 'README.md'

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   continuous-integration:
#     name: Continuous Integration
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Set up Python 3.8
#         uses: actions/setup-python@v3
#         with:
#           python-version: "3.10"

#       - name: Lint Code
#         run: echo "Linting repository..."

#       - name: Run Unit Tests
#         run: echo "Running unit tests..."

#   build-and-push-ecr:
#     name: Build and Push to ECR
#     needs: continuous-integration
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Install Required Utilities
#         run: |
#           sudo apt-get update && sudo apt-get install -y jq unzip

#       - name: Install Dependencies
#         run: |
#           pip install wheel setuptools pip --upgrade
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build, Tag, and Push Docker Image to Amazon ECR
#         id: build-image
#         env:
#           ECR_REGISTRY: ${{ secrets.AWS_ECR_LOGIN_URI }}
#           ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
#           IMAGE_TAG: latest
#         run: |
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#           echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

#   continuous-deployment:
#     name: Deploy to Server
#     needs: build-and-push-ecr
#     runs-on: self-hosted
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Pull Latest Docker Image from ECR
#         run: |
#           docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.AWS_ECR_REPO_NAME }}:latest

#       - name: Stop and Remove Existing Container (if running)
#         run: |
#           docker ps -q --filter "name=mlproj" | grep -q . && docker stop mlproj && docker rm -fv mlproj || echo "No existing container found."

#       - name: Run New Docker Container
#         run: |
#           docker run -d -p 8080:8080 --name=mlproj \
#             -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
#             -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
#             -e AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
#             ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.AWS_ECR_REPO_NAME }}:latest

#       - name: Clean Up Unused Docker Images and Containers
#         run: docker system prune -f


name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Lint Code
        run: echo "Linting repository..."

      - name: Run Unit Tests
        run: echo "Running unit tests..."

  build-and-push-ecr:
    name: Build and Push to ECR
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Required Utilities
        run: |
          sudo apt-get update && sudo apt-get install -y jq unzip

      - name: Install Dependencies
        run: |
          pip install wheel setuptools pip --upgrade
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Delete Existing Image in ECR (if exists)
        run: |
          IMAGE_TAG="latest"
          ECR_REGISTRY=${{ secrets.AWS_ECR_LOGIN_URI }}
          ECR_REPOSITORY=${{ secrets.AWS_ECR_REPO_NAME }}

          IMAGE_EXISTS=$(aws ecr describe-images --repository-name $ECR_REPOSITORY --query 'imageDetails[?imageTags[0]==`latest`].imageDigest' --output text)
          if [ -n "$IMAGE_EXISTS" ]; then
            aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids imageDigest=$IMAGE_EXISTS
            echo "Deleted existing image: $IMAGE_EXISTS"
          else
            echo "No existing image found in ECR."
          fi

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_LOGIN_URI }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

  continuous-deployment:
    name: Deploy to Server
    needs: build-and-push-ecr
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Clean Up All Docker Memory (Containers, Images, Networks, Volumes)
        run: |
          docker stop $(docker ps -aq) || true
          docker rm $(docker ps -aq) || true
          docker rmi -f $(docker images -aq) || true
          docker network prune -f
          docker volume prune -f
          docker system prune -af
          echo "Docker memory cleared."

      - name: Pull Latest Docker Image from ECR
        run: |
          docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.AWS_ECR_REPO_NAME }}:latest

      - name: Run New Docker Container
        run: |
          docker run -d -p 8080:8080 --name=mlproj \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
            ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.AWS_ECR_REPO_NAME }}:latest
